# constants.py
USER_TABLE = "User"
ACTIVITY_TABLE = "Activity"
TRACKPOINT_TABLE = "TrackPoint"

TABLE_CREATION_ORDER = [USER_TABLE, ACTIVITY_TABLE, TRACKPOINT_TABLE]
TABLE_DELETION_ORDER = [TRACKPOINT_TABLE, ACTIVITY_TABLE, USER_TABLE]
